.TH qmail-bfrmt 8 "" openqmail
.SH NAME
qmail-bfrmt \- run a program before invoking \fBqmail-remote\fR
.SH SYNOPSIS
.B qmail-bfrmt
.SH DESCRIPTION
\fBqmail-bfrmt\fR plugs into the pipe \fIqmail-rspawn\fR\->\fIqmail-remote\fR.
It reads a series of remote delivery commands from \fBqmail-rspawn\fR. Then it 
reads \fIprogram\fR from its config file \fIQPRFX/etc/beforemote\fR.
If \fIprogram\fR is a valid executable file, it will be invoked instead of
\fIqmail-remote\fR.
.P
\fIprogram\fR can be splitted into multiple \fIprograms\fR as long the pipe
\fIqmail-rspawn\fR->\fIprogram\fR->\fIqmail-remote\fR will not be broken.
\fBqmail-remote\fR have to be the last program in the pipe and can be called
one time only.
.P
If \fIprogram\fR is invalid, \fBqmail-bfrmt\fR writes a warning to syslog.
If the first line of the config file is empty, logging will be disabled.
.SH CONFIG FILE
\fBqmail-bfrmt\fR reads the first line from \fIQPRFX/etc/beforemote\fR.
If the config file doesn't exitst or something went wrong, \fIqmail-remote\fR
will be executed.

.SH "SEE ALSO"
beforeremote(5),
qmail-send(8),
qmail-remote(8),
qmail-rspawn(8)
