#!/bin/sh
#********************************************************************************
# eQmail-1.10 install script
#
# Having a comfortable shell like bash available always would make
# things much easier and the code more compact!
#********************************************************************************
QMAILDIR=`head -1 conf-qmail`
. inc/getids.inc

# man pages
for i in 1 5 7 8 ; do
  [ -d $QMAILDIR/man/man$i ] || mkdir -p $QMAILDIR/man/man$i
  cp man/$i/* $QMAILDIR/man/man$i
done

chmod -R 0644 $QMAILDIR/man
chmod 0755 $QMAILDIR/man $QMAILDIR/man/*

# doc
mkdir -p $QMAILDIR/doc
cp doc/FAQ      $QMAILDIR/doc
cp doc/INSTAL*  $QMAILDIR/doc
cp doc/PIC.*    $QMAILDIR/doc
#cp README* $QMAILDIR/doc
cp doc/REMOVE.* $QMAILDIR/doc
cp doc/SENDMAIL $QMAILDIR/doc
cp doc/TEST.*   $QMAILDIR/doc
cp doc/UPGRADE  $QMAILDIR/doc

chmod 0644 $QMAILDIR/doc/*

# top level
T=$QMAILDIR           # just to shortening next commands (T: tmp)
mkdir -p $T/alias $T/bin $T/control $T/queue $T/users
chmod 2755         $QMAILDIR/alias
chown $UIDA:$GIDQ  $QMAILDIR/alias
chown $UIDO:$GIDQ  $QMAILDIR/bin $QMAILDIR/control $QMAILDIR/users

# queue
T=$QMAILDIR/queue     # just to shortening next commands (T: tmp)
mkdir -p $T/bounce $T/lock $T/pid
i=0
until [ $i -eq `head -1 conf-split` ]
do
  # Create splitted queue subdirectories
  mkdir -p $T/info/$i $T/intd/$i $T/local/$i $T/mess/$i $T/remote/$i $T/todo/$i
  i=$(($i+1))
done
# set all:
chown -R $UIDQ:$GIDQ  $QMAILDIR/queue
chmod -R 0750         $QMAILDIR/queue
# set new: bounce, info, local, remote
chown -R $UIDS:$GIDQ  $T/bounce $T/info $T/local $T/remote
chmod -R 0700         $T/info $T/intd $T/local $T/pid $T/remote

# special files in 'lock'
dd if=/dev/zero of=$QMAILDIR/queue/lock/tcpto bs=2048 count=1 status=none
chown $UIDR:$GIDQ  $QMAILDIR/queue/lock/tcpto
chmod 0644         $QMAILDIR/queue/lock/tcpto

dd if=/dev/zero of=$QMAILDIR/queue/lock/sendmutex bs=8 count=0 status=none
chown $UIDS:$GIDQ  $QMAILDIR/queue/lock/sendmutex
chmod 0600         $QMAILDIR/queue/lock/sendmutex

mkfifo -m 622      $QMAILDIR/queue/lock/trigger 2>/dev/null
chown $UIDS:$GIDQ  $QMAILDIR/queue/lock/trigger

# bin
cp bouncesaying condredirect datemail except forward maildir2mbox \
   maildirmake mailsubj mkservercerts mkrsadhkeys predate   $QMAILDIR/bin
cp qmail-bfque qmail-bfrmt qmail-clean qmail-getpw qmail-inject \
   qmail-local qmail-lspawn qmail-newmrh qmail-newu qmail-pw2u \
   qmail-qmqpc qmail-qmqpd qmail-qmtpd qmail-qread qmail-qstat \
   qmail-queue qmail-remote qmail-rspawn qmail-send qmail-showctl \
   qmail-smtpd qmail-start qmail-tcpok qmail-tcpto          $QMAILDIR/bin
cp qreceipt qsmhook sendmail splogger tcp-env               $QMAILDIR/bin

chown $UIDO:$GIDQ  $QMAILDIR/bin/*
chmod 0755         $QMAILDIR/bin/*

cd "$QMAILDIR/bin"
chmod 0711 qmail-getpw qmail-local qmail-remote qmail-rspawn \
           qmail-clean qmail-send qmail-pw2u splogger
chmod 0700 qmail-lspawn qmail-start qmail-newu qmail-newmrh
cd $OLDPWD
chown $UIDQ:$GIDQ  $QMAILDIR/bin/qmail-queue
chmod 04711        $QMAILDIR/bin/qmail-queue

# create aliases
cd $QMAILDIR/alias
touch .qmail-root
echo root > .qmail-postmaster
[ -L .qmail-mailer-daemon ] || ln -s .qmail-postmaster .qmail-mailer-daemon
chmod 644 .*
../bin/maildirmake .Maildir
chown $UIDA:$GIDQ .*
cd $OLDPWD

# at least set rights and group of the home dir
chmod 755 $QMAILDIR ; chgrp $GIDQ $QMAILDIR

# control
. ./config

# extend $PATH (experimental)
if [ -d /ert/profile.d ] ; then
   echo "export PATH=$PATH:$QMAILDIR/bin"        > /etc/profile.d/eqmail.sh
   echo "export MANPATH=$MANPATH:$QMAILDIR/man" >> /etc/profile.d/eqmail.sh
   . /etc/profile
fi
