#!/bin/sh
#********************************************************************************
# Create qmail users and groups                                                 *
#                                                                               *
#   Author: Kai Peter, ©2013 (kp@dyndn.es)                                      *
#                                                                               *
#  Version: 0.32-beta                                                           *
#  Lisence: public domain                                                       *
#                                                                               *
# Description: I don't remember how often I did create a script to create the   *
#              necessary users ...                                              *
#              This should work on most Linux and FreeBSD ... still imperfect.  *
#********************************************************************************

# have to be run as root
if [ `id -u` -ne 0 ] ; then echo "$0 have to be run as root!" ; exit 1 ; fi

#********************************************************************************
# define the first GID/UID
STARTGID=
STARTUID=200
HOME=`head -1 conf-qmail`

([ -z $STARTGID ] || [ -z $STARTUID ]) && echo "Invalid ID! Aborting!"
#([ -z $STARTGID ] || [ -z $STARTUID ]) && MSG="Invalid ID! Aborting!"
#( [ -n $MSG ] && echo $MSG ; exit )
[ $STARTGID ] && [ $STARTUID ] || exit;

#********************************************************************************
# search for the tool to create a group
#
PRG=$(which groupadd 2>/dev/null) || \
PRG=$(which addgroup 2>/dev/null) || \
PRG=$(which pw 2>/dev/null)
# FreeBSD's tool 'pw' is special: 'pw groupadd -g 200 -n qmail'
if [ "$PRG" ] && [ $PRG = "/usr/sbin/pw" ] ; then PRG=$PRG" groupadd" ; N="-n" ; fi
# Error:
[ "$PRG" ] || echo "Didn't know how to add groups! Aborting!"
[ "$PRG" ] || exit;

# creating groups
if [ $STARTGID ] ; then GID="$STARTGID" ; PRG=$PRG" -g" ; fi
for G in `head -2 conf-groups`
do
  $PRG $GID $N $G && echo "Added group $G"
  [ $GID ] && GID=$(($GID+1))	# increment the next GID
done

#********************************************************************************
# search for the tool to create users (usually 'adduser 'or 'useradd')
PRG=$(which useradd 2>/dev/null) || \
PRG=$(which adduser 2>/dev/null)
# on FreeBSD we need pw and the '-n <user>' switch (the cmd is a bit different:
# '$> pw useradd -g qmail -s /bin/nologin -c "" -d /var/qmail -u 200 -n <user>' )
if [ `uname | tr '/:[A-Z]' '..[a-z]'` = "freebsd" ] ; then
#   PRG="/usr/sbin/pw useradd" ; N="-n" ; fi
   PRG=$(which pw 2>/dev/null)" useradd" ; N="-n" ; fi

# Error:
[ $PRG ] ||  echo "Didn't know how to create users! Aborting!"
[ $PRG ] || exit;

# users
if [ $STARTUID ] ; then NUID="$STARTUID" ; fi
for U in `head -8 conf-users`
do
  i=$(($i+1))  # increment the loop counter
#  if [ $U != "root" ] ; then
  if [ `id -u $U` 2>/dev/null -ne 0 ] ; then
	H=$HOME ; GID="qmail"
    if [ $U = "alias" ] ; then H=$HOME/alias ; fi
	# switch the group (the first 4 users have 'qmail', than 'nofiles')
#    if [ $NUID -ge $(($STARTUID+4)) ] ; then GID="nofiles" ; fi
    if [ $i -ge 5 ] ; then GID="nofiles" ; fi
    #
    [ $NUID ] && SETNUID="-u $NUID"
    echo -n "$i: "
    $PRG -g $GID -s /sbin/nologin $SETNUID -c "" -d $H $N $U && \
	echo "Added user $U with group $GID!"
    [ $NUID ] && NUID=$(($NUID+1))  # increment the next NUID
  fi
done
