#!/bin/sh

# Update temporary RSA and DH keys
# Frederik Vermeulen 2004-05-31 GPL

umask 0077 || exit 0

export PATH="$PATH:/usr/local/bin/ssl:/usr/sbin"

openssl genrsa -out /usr/local/qmail/control/rsa2048.new 2048 &&
chmod 600 /usr/local/qmail/control/rsa2048.new &&
chown qmaild:qmail /usr/local/qmail/control/rsa2048.new &&
mv -f /usr/local/qmail/control/rsa2048.new /usr/local/qmail/control/rsa2048.pem
echo

openssl dhparam -2 -out /usr/local/qmail/control/dh2048.new 2048 &&
chmod 600 /usr/local/qmail/control/dh2048.new &&
chown qmaild:qmail /usr/local/qmail/control/dh2048.new &&
mv -f /usr/local/qmail/control/dh2048.new /usr/local/qmail/control/dh2048.pem
