#!/bin/sh
#********************************************************************************
# search for existing qmail installation(s)
#
# Part of configure 
#

QMAILDIR="qlibs"

# do not call this script directily
[ `basename $0` = "find-qmaildir" ] && echo -n `basename $0` "couldn't run alone!" \
  && echo " Aborting!" && exit 1

invalidInput() { printf "Invalid input! Aborting!\n"; exit 1; }

findit() {
  printf "\n  Found multiple possible installations:\n"
  # check 'conf-build' exists (has precedence over 'qmail-home')
  [ "$QMAILDIR" ] && TMP=`cat instdir.tmp | grep "$QMAILDIR" 2>/dev/null`
  [ "$TMP" ] && [ "$QMAILDIR" = "$TMP" ] && D="$TMP" && \
    printf "  ... using matching value of 'conf-build': " && return
  # check 'autocf-qprfx'
  [ -f autocf-qprfx ] && D=`head -1 autocf-qprfx`
  [ "$D" ] && TMP=`cat instdir.tmp | grep "$D"`
  [ "$TMP" ] && [ "$TMP" = "$D" ] && \
    printf "  ... using matching value of 'autocf-qprfx': " && return
  # last case: manual selection by user
  i=0
  until [ $i -eq $n ] ; do
    i=$(($i+1))
    printf "    [$i] " ; head -$i instdir.tmp | tail -1
  done
  printf "\n\033[1m  Select number: \033[0m"
  read  s
  [[ $s =~ ^-?[0-9]+$ ]] || invalidInput $s    # check for integer input
  [ $s -gt 0 ] && [ $s -le $n ] && D=`head -$s instdir.tmp | tail -1`
  [ -z $D ] && invalidInput $s
  printf "  ... using "
}

printf "Searching for *qmail ... "
# get the number of (possible) installation(s)
#n=`find /{usr/local,var}/*/bin/ -name qmail-smtpd -type f 2>/dev/null | \
#   xargs dirname | xargs dirname | tee instdir.tmp | wc -l`

n=`find /{usr/local,/usr}/lib/ -name qlibs.a -type f | \
   xargs dirname | tee instdir.tmp | wc -l`

[ $n -gt 1 ] && echo 111 #findit
[ $n -eq 0 ] && D=""    #echo "Nothing!" && exit
[ $n -eq 1 ] && D=`head -1 instdir.tmp`
# 
[ -z "$D" ] && echo "Couldn't find *qmail home! Aborting!" && exit

QMAILDIR=$D
echo $QMAILDIR
#echo "$QMAILDIR" > autocf-qprfx  #instdir.tmp
