#!/bin/sh
#************************************************************************
# Get users/groups from 'conf-{users,groups}'.  Used by the 'configure' *
# and 'install' scripts.                                                *
#************************************************************************
UIDA="$(id -u `head -1 conf-users | tail -1`)"
UIDD="$(id -u `head -2 conf-users | tail -1`)" || echo "error 1"
UIDL="$(id -u `head -3 conf-users | tail -1`)"
UIDO="$(id -u `head -4 conf-users | tail -1`)"
UIDP="$(id -u `head -5 conf-users | tail -1`)"
UIDQ="$(id -u `head -6 conf-users | tail -1`)"
UIDR="$(id -u `head -7 conf-users | tail -1`)"
UIDS="$(id -u `head -8 conf-users | tail -1`)"

GIDQ="$(getent group `head -1 conf-groups | tail -1` | cut -d: -f3)"
GIDN="$(getent group `head -2 conf-groups | tail -1` | cut -d: -f3)"

#********************************************************************************
# checking that users from conf-users are exists (excluding 'alias')
for i in 2 3 4 5 6 7 8
do
  id -u `head -$i conf-users | tail -1` 2>&1 >/dev/null
  if [ $? -ne 0 ] ; then echo "Create users first!" ; exit 1 ; fi
done

#********************************************************************************
# create file 'auto_uids.c'
#. cfg/getids.inc
echo -n "Checking users and groups"
echo "int auto_uida = $UIDA;"  > auto_uids.c
echo "int auto_uidd = $UIDD;" >> auto_uids.c
echo "int auto_uidl = $UIDL;" >> auto_uids.c
echo "int auto_uido = $UIDO;" >> auto_uids.c
echo "int auto_uidp = $UIDP;" >> auto_uids.c
echo "int auto_uidq = $UIDQ;" >> auto_uids.c
echo "int auto_uidr = $UIDR;" >> auto_uids.c
echo "int auto_uids = $UIDS;" >> auto_uids.c
echo "int auto_gidq = $GIDQ;" >> auto_uids.c
echo "int auto_gidn = $GIDN;" >> auto_uids.c
echo " ... auto_uids.c created!"

#. ./cfg/save-conf.inc      # save values of conf-* files temporarily
