#!/bin/sh

. ./conf-build

install_libs() { cp *.a $OFILES "$LIBDIR" ; }
install_hdrs() { cp include/*.h "$HDRDIR" ; }

echo -n "Installing qlibs ..."
mkdir -p "$LIBDIR" "$HDRDIR" 2>/dev/null

[ "$LIBDIR" ] && install_libs
[ "$HDRDIR" ] && install_hdrs

echo " done!"
